#!/usr/bin/env python
# Parser for DE/SQR benchmark results generated by benchmark_real_data_de_sqr.py
# Focuses on CLEAR, DE, and SQR variants, and can include lambda/gamma_1 columns

import os
import sys
import numpy as np
import pandas as pd
from pathlib import Path
import argparse
import glob
import re

# Import utilities from the original combine script
script_dir = os.path.dirname(os.path.abspath(__file__))
if script_dir not in sys.path:
    sys.path.append(script_dir)
sys.path.append(os.path.join(script_dir, '..','..', 'src'))

from utils import format_metric_name, write_latex_table


def load_de_sqr_results(results_dir: str, coverage: int):
    """
    Load all SQR/DE benchmark result CSV files for a given coverage.

    Args:
        results_dir: Directory containing the CSV files
        coverage: Coverage percentage (e.g., 95)

    Returns:
        Dictionary mapping dataset names to DataFrames
    """
    dataset_results = {}

    csv_pattern = os.path.join(results_dir, f"de_sqr_results_*_{coverage}.csv")
    csv_files = glob.glob(csv_pattern)

    print(f"Found {len(csv_files)} CSV files in {results_dir}")

    for csv_file in csv_files:
        filename = os.path.basename(csv_file)
        match = re.search(r'de_sqr_results_(.+)_' + str(coverage), filename)

        if match:
            dataset = match.group(1)
            try:
                df = pd.read_csv(csv_file)
                # Filter out empty rows if any
                if 'method' in df.columns:
                    df = df.dropna(subset=['method'])
                dataset_results[dataset] = df
                n_runs = df['run'].nunique() if 'run' in df.columns else 1
                print(f"  Loaded {dataset}: {len(df)} rows, {n_runs} runs")
            except Exception as e:
                print(f"  Error loading {csv_file}: {e}")

    return dataset_results


def aggregate_metrics_for_methods(dataset_results: dict, methods_mapping: dict):
    """
    Aggregate metrics across runs for specified methods.

    Args:
        dataset_results: Dictionary of dataset -> DataFrame
        methods_mapping: Dictionary mapping display names to method names in CSV

    Returns:
        Dictionary with aggregated results
    """
    aggregated_data = {}

    for dataset, df in dataset_results.items():
        aggregated_data[dataset] = {}

        for display_name, csv_method in methods_mapping.items():
            method_data = df[df['method'] == csv_method] if 'method' in df.columns else pd.DataFrame()

            if len(method_data) == 0:
                print(f"  Warning: No data found for {csv_method} in {dataset}")
                continue

            metric_stats = {}
            metrics = [
                'PICP', 'NIW', 'MPIW', 'QuantileLoss', 'ExpectileLoss',
                'CRPS', 'AUC', 'NCIW', 'IntervalScoreLoss'
            ]

            for metric in metrics:
                if metric in method_data.columns:
                    values = method_data[metric].dropna().values
                    if len(values) > 0:
                        metric_stats[metric] = {
                            'mean': float(np.mean(values)),
                            'std': float(np.std(values)),
                            'median': float(np.median(values)),
                            'min': float(np.min(values)),
                            'max': float(np.max(values)),
                            'values': values.tolist(),
                        }

            # Store calibration parameters (available only for CLEAR)
            if csv_method == 'CLEAR':
                if 'lambda' in method_data.columns:
                    lambda_values = method_data['lambda'].dropna().values
                    if len(lambda_values) > 0:
                        metric_stats['lambda'] = {
                            'mean': float(np.mean(lambda_values)),
                            'median': float(np.median(lambda_values)),
                            'min': float(np.min(lambda_values)),
                            'max': float(np.max(lambda_values)),
                        }

                if 'gamma' in method_data.columns:
                    gamma_values = method_data['gamma'].dropna().values
                    if len(gamma_values) > 0:
                        metric_stats['gamma'] = {
                            'mean': float(np.mean(gamma_values)),
                            'median': float(np.median(gamma_values)),
                            'min': float(np.min(gamma_values)),
                            'max': float(np.max(gamma_values)),
                        }

            aggregated_data[dataset][display_name] = metric_stats

    return aggregated_data


def generate_metric_table(
    aggregated_data: dict,
    metric: str,
    coverage: int,
    output_dir: str,
    decimal_places: int = 4,
    landscape_mode: bool = False,
    include_calibration_params: bool = False,
):
    """
    Generate a LaTeX table for a specific metric, optionally with extra columns for lambda and gamma_1.
    """
    higher_is_better_metrics = {'PICP': True}
    higher_is_better = higher_is_better_metrics.get(metric, False)

    metric_decimals = {
        'PICP': 2,
        'NIW': 3,
        'MPIW': 3,
        'QuantileLoss': 3,
        'CRPS': 3,
        'AUC': 3,
        'NCIW': 3,
        'ExpectileLoss': 3,
        'IntervalScoreLoss': 3,
    }
    decimals = metric_decimals.get(metric, decimal_places)

    formatted_metric = format_metric_name(metric.lower())
    caption = (
        f"DE-SQR {formatted_metric} at {coverage}\\% prediction intervals, aggregated across 10 seeds. "
        "CLEAR consists of the deep ensemble (DE) and the simultaneous quantile regressor (SQR). "
        "DE-conformal is the conformalized (calibrated) deep ensemble and SQR-conformal is the conformalized simultaneous quantile regressor. "
    )

    if metric != 'PICP':
        caption += "Values $\\geq 100$ or $< 0.01$ are presented in scientific notation with 1 decimal place. "
        if higher_is_better:
            caption += "\\textbf{Bold} values are the maximum (best) for that dataset, while \\underline{underlined} values indicate the second-best result."
        else:
            caption += "\\textbf{Bold} values are the minimum (best) for that dataset, while \\underline{underlined} values indicate the second-best result."

    method_order = ['CLEAR', 'DE', 'SQR', 'DE-conformal', 'SQR-conformal']

    # Adjust table structure based on whether to include calibration parameters
    if include_calibration_params:
        tabular_cols = "l" + "c" * len(method_order) + "cc"
        header_row = "Dataset & CLEAR & DE & SQR & DE\\text{-}conformal & SQR\\text{-}conformal & $\\lambda$ & $\\gamma_1$ \\\\" 
    else:
        tabular_cols = "l" + "c" * len(method_order)
        header_row = "Dataset & CLEAR & DE & SQR & DE\\text{-}conformal & SQR\\text{-}conformal \\\\" 

    table_lines = [
        "\\begin{table}[!htbp]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{tab:de_sqr_{metric.lower()}_{coverage}}}",
        "\\small",
        "\\resizebox{\\columnwidth}{!}{%",
        f"\\begin{{tabular}}{{{tabular_cols}}}",
        "\\toprule",
        header_row,
        "\\midrule",
    ]

    for dataset in sorted(aggregated_data.keys()):
        row = [dataset.replace('_', '\\_')]

        # Ranking for bold/italic
        values_for_ranking = []
        for method in method_order:
            if method in aggregated_data[dataset] and metric in aggregated_data[dataset][method]:
                mean_val = aggregated_data[dataset][method][metric]['mean']
                if mean_val is not None and not np.isnan(mean_val):
                    values_for_ranking.append((mean_val, method))

        if values_for_ranking:
            values_for_ranking.sort(key=lambda x: x[0], reverse=higher_is_better)
            best_method = values_for_ranking[0][1]
            second_best_method = values_for_ranking[1][1] if len(values_for_ranking) > 1 else None
        else:
            best_method = None
            second_best_method = None

        # Values per method
        for method in method_order:
            if method in aggregated_data[dataset] and metric in aggregated_data[dataset][method]:
                stats = aggregated_data[dataset][method][metric]
                mean_val = stats.get('mean')
                std_val = stats.get('std')

                if mean_val is None or np.isnan(mean_val):
                    row.append('-')
                    continue

                use_scientific_mean = False if metric == 'PICP' else (abs(mean_val) >= 100 or abs(mean_val) < 0.01)
                formatted_mean = f"{mean_val:.1e}" if use_scientific_mean else f"{mean_val:.{decimals}f}"

                has_std = std_val is not None and not np.isnan(std_val)
                if has_std:
                    use_scientific_std = False if metric == 'PICP' else (abs(std_val) >= 100 or abs(std_val) < 0.01)
                    formatted_std = f"{std_val:.1e}" if use_scientific_std else f"{std_val:.{decimals}f}"
                    cell_content = f"{formatted_mean} $\\pm$ {formatted_std}"
                else:
                    cell_content = formatted_mean

                if metric != 'PICP':
                    if method == best_method:
                        cell_content = f"\\textbf{{{cell_content}}}"
                    elif method == second_best_method:
                        cell_content = f"\\underline{{{cell_content}}}"
                row.append(cell_content)
            else:
                row.append('-')

        # CLEAR calibration parameters (only if requested)
        if include_calibration_params:
            lambda_str = '-'
            gamma_str = '-'
            if 'CLEAR' in aggregated_data[dataset]:
                clear_stats = aggregated_data[dataset]['CLEAR']
                if 'lambda' in clear_stats:
                    # Use mean of lambda values across runs
                    lambda_mean = clear_stats['lambda']['mean']
                    lambda_str = f"{lambda_mean:.3f}"
                if 'gamma' in clear_stats:
                    # Use mean of gamma values across runs  
                    gamma_mean = clear_stats['gamma']['mean']
                    gamma_str = f"{gamma_mean:.3f}"

            row.append(lambda_str)
            row.append(gamma_str)

        table_lines.append(" & ".join(row) + " \\\\")

    table_lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "}",
        "\\end{table}",
    ])

    output_file = os.path.join(output_dir, f"table-de-sqr-{coverage}-{metric.lower()}.tex")
    write_latex_table(table_lines, output_file, landscape_mode)
    print(f"  Created table for {metric} at {output_file}")


def generate_calibration_parameters_table(aggregated_data: dict, coverage: int, output_dir: str, landscape_mode: bool = False):
    """
    Generate a table showing CLEAR calibration parameters (lambda and gamma).
    """
    caption = (
        f"CLEAR calibration parameters $\\lambda$ and $\\gamma_1$ for {coverage}\\% prediction intervals "
        f"(SQR/DE benchmark). Showing mean values across runs."
    )

    table_lines = [
        "\\begin{table}[!htbp]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{tab:de_sqr_calibration_{coverage}}}",
        "\\small",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Dataset & $\\lambda$ & $\\gamma_1$ \\\\",
        "\\midrule",
    ]

    for dataset in sorted(aggregated_data.keys()):
        if 'CLEAR' in aggregated_data[dataset]:
            clear_data = aggregated_data[dataset]['CLEAR']
            lambda_str = '-'
            gamma_str = '-'
            if 'lambda' in clear_data:
                lambda_mean = clear_data['lambda']['mean']
                lambda_str = f"{lambda_mean:.3f}"
            if 'gamma' in clear_data:
                gamma_mean = clear_data['gamma']['mean']
                gamma_str = f"{gamma_mean:.3f}"
            table_lines.append(" & ".join([dataset.replace('_', '\\_'), lambda_str, gamma_str]) + " \\\\")

    table_lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ])

    output_file = os.path.join(output_dir, f"table-sqr-de-calibration-{coverage}.tex")
    write_latex_table(table_lines, output_file, landscape_mode)
    print(f"Created calibration parameters table at {output_file}")


def generate_summary_statistics(aggregated_data: dict, coverage: int, output_dir: str):
    """
    Generate a summary CSV with mean values across all datasets for the three methods.
    """
    summary_data = []
    metrics = ['PICP', 'NIW', 'MPIW', 'QuantileLoss', 'ExpectileLoss', 'CRPS', 'AUC', 'NCIW', 'IntervalScoreLoss']

    for method in ['CLEAR', 'DE', 'SQR', 'DE-conformal', 'SQR-conformal']:
        method_summary = {'Method': method}
        for metric in metrics:
            values = []
            for dataset in aggregated_data:
                if method in aggregated_data[dataset] and metric in aggregated_data[dataset][method]:
                    values.append(aggregated_data[dataset][method][metric]['mean'])
            if values:
                method_summary[f'{metric}_mean'] = float(np.mean(values))
                method_summary[f'{metric}_std'] = float(np.std(values))
        summary_data.append(method_summary)

    summary_df = pd.DataFrame(summary_data)
    summary_file = os.path.join(output_dir, f"de_sqr_summary_{coverage}.csv")
    summary_df.to_csv(summary_file, index=False)
    print(f"Created summary statistics at {summary_file}")

    # Console print (compact)
    print("\nSummary Statistics (mean across all datasets):")
    print("-" * 80)
    print(f"{'Method':<10}", end='')
    for metric in ['PICP', 'NIW', 'MPIW', 'NCIW', 'CRPS', 'AUC']:
        print(f"{metric:>10}", end='')
    print()
    print("-" * 80)
    for _, row in summary_df.iterrows():
        display_name = row['Method'].replace('-conformal', r"-conformal").replace('_', '\\_')
        print(f"{display_name:<10}", end='')
        for metric in ['PICP', 'NIW', 'MPIW', 'NCIW', 'CRPS', 'AUC']:
            key = f'{metric}_mean'
            print(f"{row[key]:>10.4f}" if key in row and not pd.isna(row[key]) else f"{'N/A':>10}", end='')
        print()


def main():
    parser = argparse.ArgumentParser(description='Parse SQR/DE benchmark results and generate LaTeX tables')
    parser.add_argument('--results_dir', type=str, default='../../results/de_sqr', help='Directory containing SQR/DE benchmark CSV files')
    parser.add_argument('--output_dir', type=str, default='../tex_tbls/de_sqr', help='Directory to save output tables')
    parser.add_argument('--coverage', type=int, default=95, help='Coverage percentage (default: 95)')
    parser.add_argument('--metrics', type=str, default='all', help="Comma-separated list of metrics to process, or 'all'")
    parser.add_argument('--landscape_mode', action='store_true', help='Generate tables in landscape mode')
    parser.add_argument('--include_calibration_in_metrics', action='store_true', 
                       help='Include lambda and gamma columns in all metric tables (default: separate table only)')
    parser.add_argument('--calibration_metric', type=str, default=None,
                       help='Specific metric to include calibration parameters with (e.g., "QuantileLoss")')
    parser.add_argument('--skip_separate_calibration', action='store_true',
                       help='Skip generating the separate calibration parameters table')

    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    print(f"\nLoading SQR/DE benchmark results from {args.results_dir}")
    dataset_results = load_de_sqr_results(args.results_dir, args.coverage)
    if not dataset_results:
        print('No results found!')
        return

    methods_mapping = {
        'CLEAR': 'CLEAR',
        'DE': 'DE_calibrated',
        'SQR': 'SQR_uncalibrated',
        'DE-conformal': 'DE_conformal',
        'SQR-conformal': 'SQR_conformal',
    }

    print("\nAggregating results across runs...")
    aggregated_data = aggregate_metrics_for_methods(dataset_results, methods_mapping)

    metrics = (
        ['PICP', 'NIW', 'MPIW', 'QuantileLoss', 'ExpectileLoss', 'CRPS', 'AUC', 'NCIW', 'IntervalScoreLoss']
        if args.metrics == 'all' else [m.strip() for m in args.metrics.split(',')]
    )

    print("\nGenerating LaTeX tables...")
    for metric in metrics:
        # Determine if this metric should include calibration parameters
        include_calibration = False
        if args.include_calibration_in_metrics:
            include_calibration = True
        elif args.calibration_metric and metric.lower() == args.calibration_metric.lower():
            include_calibration = True
            
        generate_metric_table(aggregated_data, metric, args.coverage, args.output_dir, 
                            landscape_mode=args.landscape_mode, 
                            include_calibration_params=include_calibration)

    # Generate separate calibration parameters table unless skipped
    if not args.skip_separate_calibration:
        generate_calibration_parameters_table(aggregated_data, args.coverage, args.output_dir, args.landscape_mode)
    
    generate_summary_statistics(aggregated_data, args.coverage, args.output_dir)

    print(f"\nProcessing complete! Tables saved to {args.output_dir}")
    print("\nGenerated files:")
    print(f"  - Metric tables: table-de-sqr-{args.coverage}-[metric].tex")
    if not args.skip_separate_calibration:
        print(f"  - Calibration parameters: table-de-sqr-calibration-{args.coverage}.tex")
    print(f"  - Summary statistics: de_sqr_summary_{args.coverage}.csv")
    
    # Print information about calibration parameter inclusion
    if args.include_calibration_in_metrics:
        print(f"\nNote: Lambda and gamma columns included in all metric tables.")
    elif args.calibration_metric:
        print(f"\nNote: Lambda and gamma columns included only in {args.calibration_metric} table.")
    else:
        print(f"\nNote: Lambda and gamma parameters are in separate calibration table only.")


if __name__ == '__main__':
    main()

# To run it
# python combine_improved_integrated_results_markdown.py --results_dir ../../results/de_sqr --output_dir ./tex_tbls/de_sqr --coverage 95